version: "3"
services:
  test:
    build: .
    volumes:
      - ./:/working
    container_name: yenta
    working_dir: /working
    ports:
      - 8080:8080
    environment:
      - PYTHONPATH=/working
    tty: true
